export const months = [
  'january', 'february', 'march', 'april', 'may', 'june',
  'july', 'august', 'september', 'october', 'november', 'december',
];

export const measureTypes = ['PAC', 'PTC', 'FAC', 'FTC', 'PTM', 'FTM', 'PAM', 'FAM', 'P_PROGRESS', 'F_PROGRESS'];

export const measureTypeMeta = {
  PAC: { label: 'PAC', description: 'Planned physical cumulative' },
  PTC: { label: 'PTC', description: 'Physical target cumulative' },
  FAC: { label: 'FAC', description: 'Actual financial cumulative' },
  FTC: { label: 'FTC', description: 'Financial target cumulative' },
  PTM: { label: 'PTM', description: 'Physical target monthly' },
  FTM: { label: 'FTM', description: 'Financial target monthly' },
  PAM: { label: 'PAM', description: 'Physical achieved monthly' },
  FAM: { label: 'FAM', description: 'Financial achieved monthly' },
  P_PROGRESS: { label: 'P_PROGRESS', description: 'Physical progress tracker' },
  F_PROGRESS: { label: 'F_PROGRESS', description: 'Financial progress tracker' },
};

export const budgetLineConfig = {   
  Infrastructure: { color: '#38bdf8' },
  Transport: { color: '#f59e0b' },  
  Utilities: { color: '#22c55e' },
  Housing: { color: '#8b5cf6' },   
  Community: { color: '#ef4444' },   
  'Essential Maintenance of Government Housing Schemes': { color: '#14b8a6' },
  Techcity: { color: '#f97316' },
  'Clean Sri Lanka': { color: '#22c55e' },
  'Tourism Promotion and City Branding': { color: '#0ea5e9' },  
  'Siyak Nagara': { color: '#0891b2' },
  'UDA Own Funded Projects': { color: '#6366f1' },
  'Jaffna Townhall': { color: '#ec4899' },
  'Solid Waste Management': { color: '#10b981' },
  'TechCity': { color: '#f59e0b' },
  'Consultancy Projects': { color: '#8b5cf6' },
  '25 Cities': { color: '#06b6d4' },
  '10 Cities': { color: '#a855f7' },
};

const emptyMeasures = () => measureTypes.reduce((acc, key) => { 
  acc[key] = months.reduce((mAcc, m) => {
    mAcc[m] = ''; 
    return mAcc;
  }, {}); 
  return acc; 
}, {});

export const INITIAL_PROJECTS = [
  {
    id: 1772532181322,
    department: 'Dept: Urban Dev & Special Proj',
    district: 'Polonnaruwa',
    budgetLine: 'Clean Sri Lanka',
    projectNumber: 39,
    projectName: 'Renovation of Facility Centre at Lankapura',
    startDate: '2025-09-18',
    endDate: '2026-01-15',
    npd: '',
    tec: '24.50',
    allocation2026: '10.69',
    awardedSum: '17442375',
    revisedCost: '',
    physicalProgress: '37%',
    financialProgress: '39%',
    kpi: '100% Completion of Projects',
    output: 'Completion of sanitary facility building for Local & Foreign. tourists…',
    outcome: '. Improvement of Toilet block               ( Ladies/ Gents & Disable)…',
    responsibleOfficer: 'Ms.Erandi Senevirathne Additional Director (Architect)0772350159',
    reasonsForDelays: '',
    remarks: '',
    milestones: [],
    risks: [],
    documents: [],
    monthlyProgress: {},
    measures: {
      ...emptyMeasures(),
      outcome: '. Improvement of Toilet block               ( Ladies/ Gents & Disable)…',
      output: 'Completion of sanitary facility building for Local & Foreign. tourists…',
    },
  },
  {
    id: 1772532190315,
    department: 'Dept: Urban Dev & Special Proj',
    district: 'Kurunegala',
    budgetLine: 'Clean Sri Lanka', 
    projectNumber: 40, 
    projectName: 'Construction and renovation of facility center at Badagamuwa Forest Pa…',
    startDate: '2025-09-18',
    endDate: '2026-01-15',
    npd: '',
    tec: '24.71',
    allocation2026: '10.51', 
    awardedSum: '16889512.95',
    revisedCost: '', 
    physicalProgress: '58%',
    financialProgress: '38%', 
    kpi: '100% Completion of Projects',
    output: 'Completion of sanitary facility building & Camping facility building f…',
    outcome: '. Toilet block  ( Ladies/ Gents & Disable)                      . RCC …',
    responsibleOfficer: 'Mrs.Rasika Sahabandu.    ctg.D.Director   0760492293',
    reasonsForDelays: '', 
    remarks: '', 
    milestones: [], 
    risks: [],
    documents: [],
    monthlyProgress: {},
    measures: {
      ...emptyMeasures(),
      outcome: '. Toilet block  ( Ladies/ Gents & Disable)                      . RCC …',
      output: 'Completion of sanitary facility building & Camping facility building f…',
    },
  },
  {
    id: 1772532197371, 
    department: 'Dept: Urban Dev & Special Proj',
    district: 'Matale',  
    budgetLine: 'Clean Sri Lanka',     
    projectNumber: 41,   
    projectName: 'Development of Tourist Sanitary facilities at Hotel Junction Sigiriya',
    startDate: '',    
    endDate: '',      
    npd: '',      
    tec: '31.9Mn', 
    allocation2026: '', 
    awardedSum: '',
    revisedCost: '',
    physicalProgress: '',
    financialProgress: '',
    kpi: '',
    output: 'Completion of sanitary facility building for Local & Foreign. tourists…',
    outcome: ' Improvement of Sanitary Facilities Toilet block               ( Ladie…',
    responsibleOfficer: 'Ms.Thathsarani Karavita, Additional Director (Architect)00760954417',
    reasonsForDelays: '',
    remarks: '',
    milestones: [], 
    risks: [],  
    documents: [],
    monthlyProgress: {}, 
    measures: {
      ...emptyMeasures(),  
      outcome: ' Improvement of Sanitary Facilities Toilet block               ( Ladie…',
      output: 'Completion of sanitary facility building for Local & Foreign. tourists…',
    },
  },
  {
    id: 1772532201866, 
    department: 'Dept: Urban Dev & Special Proj',  
    district: 'Polonnaruwa', 
    budgetLine: 'Clean Sri Lanka', 
    projectNumber: 42, 
    projectName: 'Bus halt & Sanitary facility development project, Girithale Junction',
    startDate: '', 
    endDate: '', 
    npd: '',
    tec: '28.47',
    allocation2026: '18.00',  
    awardedSum: '',
    revisedCost: '',  
    physicalProgress: '',
    financialProgress: '', 
    kpi: '',
    output: 'Complete the bus halt & make it usabale for public efficent transport …',
    outcome: '. Bus halt            . Toilet block ( Ladies/ Gents & Disable)  ',
    responsibleOfficer: 'Ms.Erandi Senevirathne Additional Director (Architect)0772350159',
    reasonsForDelays: '',
    remarks: '',
    milestones: [], 
    risks: [],
    documents: [], 
    monthlyProgress: {},  
    measures: {
      ...emptyMeasures(),  
      outcome: '. Bus halt            . Toilet block ( Ladies/ Gents & Disable)  ',
      output: 'Complete the bus halt & make it usabale for public efficent transport …',
    },
  },
  {
    id: 1772168128040,
    department: 'Dept: Urban Dev & Special Proj',
    district: 'Mullaitivu',
    budgetLine: 'Siyak Nagara',   
    projectNumber: 2,
    projectName: 'Bus stand development at Mullaitivu - stage iii',
    startDate: '2025-11-18',   
    endDate: '2026-08-14',   
    npd: '',
    tec: '70',
    allocation2026: '39.04',
    awardedSum: '48271027',   
    revisedCost: '',
    physicalProgress: '8%',
    financialProgress: '9.23',
    kpi: '100% Completion of Projects',
    output: 'Complete the bus stand and make it usable for public, efficient transportation system and enhance the commercial spaces by developing the bus stand',
    outcome: '. Supper structure finishing works   . Electrical works               ...',
    responsibleOfficer: 'Ms. Sonali Attanayaka,\n Deputy Director\n 071-4425671',
    reasonsForDelays: '',
    remarks: '',
    milestones: [],
    risks: [],
    documents: [],
    monthlyProgress: {},
    measures: {
      ...emptyMeasures(),
      outcome: '. Supper structure finishing works   . Electrical works               ...',
      output: 'Complete the bus stand and make it usable for public, efficient transportation system and enhance the commercial spaces by developing the bus stand',
    },
  },
  {
    id: 1772168137007,
    department: 'Dept: Urban Dev & Special Proj',
    district: 'Ampara',
    budgetLine: 'Siyak Nagara',
    projectNumber: 3,
    projectName: 'Weekly pola development at Ampara stage ii',
    startDate: '2025-12-24',  
    endDate: '2027-03-30',  
    npd: '',
    tec: '295.7',
    allocation2026: '50.96',
    awardedSum: '',
    revisedCost: '',  
    physicalProgress: '1%',
    financialProgress: '53.44',
    kpi: '',
    output: 'Completion of pola',
    outcome: 'Upgrading public and infrastructure facilities of the town',
    responsibleOfficer: '',
    reasonsForDelays: '',
    remarks: '',
    milestones: [],
    risks: [],
    documents: [],
    monthlyProgress: {},
    measures: {
      ...emptyMeasures(),
      outcome: 'Upgrading public and infrastructure facilities of the town',
      output: 'Completion of pola',
    },
  },
  {
    id: 1772168142936,
    department: 'Dept: Urban Dev & Special Proj',
    district: 'Anuradhapura',
    budgetLine: 'Siyak Nagara',
    projectNumber: 4,
    projectName: 'Sanitary facilities & landscape improvement at habarana, anuradhapura-stage ...',
    startDate: '2025-10-30',
    endDate: '2026-03-29',
    npd: '',
    tec: '27',
    allocation2026: '13.74',
    awardedSum: '20437027.71',
    revisedCost: '',
    physicalProgress: '20%',
    financialProgress: '6.69',
    kpi: '100% Completion of Projects',
    output: 'To improve Sanitary facilities, public gathering spaces and refreshment areas',
    outcome: '. Toilet block ( Ladies / Gents & Disable) . Coffee shops (...)',
    responsibleOfficer: 'Ms.Erandi Senevirathne Additional Director (Architect)0772350159',
    reasonsForDelays: '',
    remarks: '',
    milestones: [],
    risks: [],
    documents: [],
    monthlyProgress: {},
    measures: {
      ...emptyMeasures(),
      outcome: '. Toilet block ( Ladies / Gents & Disable) . Coffee shops (...)',
      output: 'To improve Sanitary facilities, public gathering spaces and refreshment areas',
    },
  },
];

export function fmtDMY(dateText) {
  if (!dateText) return '-';
  const d = new Date(dateText);
  if (Number.isNaN(d.getTime())) return '-';
  const day = String(d.getDate()).padStart(2, '0');
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const year = d.getFullYear();
  return `${day}/${month}/${year}`;
}
